### ISSUE TITLE
Error when following instructions in rebuilderd readme

### ISSUE THREAD

**Issue by joyliu-q** [kpcyrd/rebuilderd#56]
Hello! I'm Joy, a student working on the GSoC for in-toto-rs. 

I will be continuing Santiago's PR https://github.com/kpcyrd/rebuilderd/pull/22 on adding in-toto link attestations to rebuilderd.

### Issue
When I'm replicating the instructions in the readme, I came across an error in this step, which prevents me from continuing.

> Afterwards it's time to import some packages:
> ```
> cd tools; cargo run pkgs sync archlinux community \
>     'https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch' \
>     --architecture x86_64 --maintainer kpcyrd
> ```

I included more context and the logs of the error below. Happy to provide more information! Thanks again :D 

### When was this issue encountered?
I came across this issue last week, prior to 0.13.0's release. However, 0.13.0 also has this issue on my end.
- Branch: main branch, directly from rebuilderd github.

## Logs
```
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0:     0x55a9e93e0ae0 - std::backtrace_rs::backtrace::libunwind::trace::h63b7a90188ab5fb3
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55a9e93e0ae0 - std::backtrace_rs::backtrace::trace_unsynchronized::h80aefbf9b851eca7
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a9e93e0ae0 - std::sys_common::backtrace::_print_fmt::hbef05ae4237a4d72
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55a9e93e0ae0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h28abce2fdb9884c2
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55a9e940256f - core::fmt::write::h3b84512577ca38a8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/fmt/mod.rs:1092:17
   5:     0x55a9e93daba2 - std::io::Write::write_fmt::h465f8feea02e2aa1
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/io/mod.rs:1572:15
   6:     0x55a9e93e2c35 - std::sys_common::backtrace::_print::h525280ee0d29bdde
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55a9e93e2c35 - std::sys_common::backtrace::print::h1f0f5b9f3ef8fb78
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55a9e93e2c35 - std::panicking::default_hook::{{closure}}::ha5838f6faa4a5a8f
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:208:50
   9:     0x55a9e93e26e3 - std::panicking::default_hook::hfb9fe98acb0dcb3b
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:225:9
  10:     0x55a9e93e323d - std::panicking::rust_panic_with_hook::hb89f5f19036e6af8
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:591:17
  11:     0x55a9e90fef63 - std::panicking::begin_panic::{{closure}}::h2881e26e65559ec2
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:520:9
  12:     0x55a9e91029a9 - std::sys_common::backtrace::__rust_end_short_backtrace::hf72755a2a94f34f6
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55a9e90fee99 - std::panicking::begin_panic::h15c2be904e611030
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:519:12
  14:     0x55a9e908ad79 - tokio::runtime::blocking::shutdown::Receiver::wait::h073c770868e90f61
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/blocking/shutdown.rs:51:21
  15:     0x55a9e906ac26 - tokio::runtime::blocking::pool::BlockingPool::shutdown::h48ac0f5088b38575
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/blocking/pool.rs:145:12
  16:     0x55a9e906b25c - <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop::hcd39ceb02f241ef0
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/blocking/pool.rs:162:9
  17:     0x55a9e9085647 - core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>::h2e4b52bdd94c6483
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  18:     0x55a9e90842f4 - core::ptr::drop_in_place<tokio::runtime::Runtime>::hf9896070b08b0dfa
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:187:1
  19:     0x55a9e8eeebbf - reqwest::blocking::wait::enter::hc01fa312e78d1873
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/wait.rs:76:21
  20:     0x55a9e8eeced0 - reqwest::blocking::wait::timeout::hace97bf1d9b62b1a
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/wait.rs:13:5
  21:     0x55a9e8ed5878 - reqwest::blocking::client::ClientHandle::new::hf73bfebd75d060c6
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/client.rs:920:15
  22:     0x55a9e8ed4faf - reqwest::blocking::client::ClientBuilder::build::h1e141b4c2549f278
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/client.rs:100:9
  23:     0x55a9e8ed504c - reqwest::blocking::client::Client::new::h33cc0a8e5a4b7a59
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.4/src/blocking/client.rs:722:9
  24:     0x55a9e8a94abc - rebuildctl::schedule::archlinux::sync::hc8ddf85f9c22439c
                               at /home/joy/Projects/GSoC/rebuilderd/tools/src/schedule/archlinux.rs:134:18
  25:     0x55a9e8b04620 - rebuildctl::sync::{{closure}}::hf729556701093bb0
                               at /home/joy/Projects/GSoC/rebuilderd/tools/src/main.rs:40:30
  26:     0x55a9e8b1ef19 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha81b80f8cb797f02
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  27:     0x55a9e8b07088 - rebuildctl::main::{{closure}}::h6fc79775d6d12415
                               at /home/joy/Projects/GSoC/rebuilderd/tools/src/main.rs:102:47
  28:     0x55a9e8b1f419 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hec27939bc90dd308
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  29:     0x55a9e8aada60 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h40ff13b5e13a9663
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/park/thread.rs:263:54
  30:     0x55a9e8aed442 - tokio::coop::with_budget::{{closure}}::h2465c661d042b242
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/coop.rs:106:9
  31:     0x55a9e8b4c4f8 - std::thread::local::LocalKey<T>::try_with::hc54abe921f7fb865
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  32:     0x55a9e8b4bf9d - std::thread::local::LocalKey<T>::with::h2e983d3c9957a159
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  33:     0x55a9e8aad7ae - tokio::coop::with_budget::h4d46bd605f376470
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/coop.rs:99:5
  34:     0x55a9e8aad7ae - tokio::coop::budget::hd7d3e51c1c453581
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/coop.rs:76:5
  35:     0x55a9e8aad7ae - tokio::park::thread::CachedParkThread::block_on::hf6d327a8a6864dbf
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/park/thread.rs:263:31
  36:     0x55a9e8aed931 - tokio::runtime::enter::Enter::block_on::h6bdb29a1bea19c71
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/enter.rs:151:13
  37:     0x55a9e8abbb48 - tokio::runtime::thread_pool::ThreadPool::block_on::h600a773b584e89e9
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/thread_pool/mod.rs:71:9
  38:     0x55a9e8abbcb9 - tokio::runtime::Runtime::block_on::h66ac4d89edf27f73
                               at /home/joy/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.2/src/runtime/mod.rs:452:43
  39:     0x55a9e8b05acb - rebuildctl::main::h0553f01748004dcc
                               at /home/joy/Projects/GSoC/rebuilderd/tools/src/main.rs:293:5
  40:     0x55a9e8ab275b - core::ops::function::FnOnce::call_once::he718fecb5defa377
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  41:     0x55a9e8b4bd7e - std::sys_common::backtrace::__rust_begin_short_backtrace::h88b3e56f0aae8de1
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  42:     0x55a9e8ad0601 - std::rt::lang_start::{{closure}}::h757fc01a566eefa4
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  43:     0x55a9e93e373a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h44574effd2120c86
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/ops/function.rs:259:13
  44:     0x55a9e93e373a - std::panicking::try::do_call::h10b0bd4879c8dfb0
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:379:40
  45:     0x55a9e93e373a - std::panicking::try::h60c6780d33419e92
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:343:19
  46:     0x55a9e93e373a - std::panic::catch_unwind::h111f33e08c52e2ce
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panic.rs:431:14
  47:     0x55a9e93e373a - std::rt::lang_start_internal::h126f2e09345dbfda
                               at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/rt.rs:51:25
  48:     0x55a9e8ad05e0 - std::rt::lang_start::hc9f9e1df0ded33aa
                               at /home/joy/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  49:     0x55a9e8b0fe8c - main
  50:     0x7f0ffcbf10b3 - __libc_start_main
  51:     0x55a9e8a240ee - _start
  52:                0x0 - <unknown>
```

**Comment by kpcyrd** [comment]
hello!

Thanks for the report, I could reproduce this locally! It seems this doesn't happen with release builds (that's probably why nobody noticed yet):
```
cargo run --release -- pkgs sync archlinux community \
    'https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch' \
    --architecture x86_64 --maintainer kpcyrd
```
I'm going investigate the real root cause later, does this work as a workaround for you?

Thanks!

**Comment by joyliu-q** [comment]
That works as a workaround. Thank you!
